# Build Docker image of Turtlebot3 controller PC

name: Turtlebot3PC Docker image

on:
  # Create Docker image on push to 'master'
  push:
    branches:
      - main

env:
  # Names used to tag built Docker image
  IMAGE_NAME: turtlebotpc

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository into current runner context
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Work around (see https://github.com/docker/build-push-action/issues/37)
      # Docker does not allow mixed-case names and the repository_owner is capitalized
      - name: Lowercase necessary symbols
        run: |
            echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        
      - name: Login to Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:latest

# vim: tabstop=2 shiftwidth=2 autoindent expandtab
