# Build Docker image of Turtlebot3 controller PC

name: Turtlebot3PC Docker image

on:
  # Create Docker image on push to 'master'
  push:
    branches:
      - main

env:
  # Names used to tag built Docker image
  IMAGE_NAME: turtlebotpc
  # The local Docker image is named env.IMAGE_TAG so it can be referenced and pushed
  IMAGE_TAG: turtlebotpc:latest

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository into current runner context
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: ${{ env.IMAGE_TAG }}
          push: false

      # Login to Github Container Registry with this registry's tokens
      - name: Login to Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Push to Github Container Registry
        run: |
          # docker image tag ${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          docker image push --all-tags ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

# vim: tabstop=2 shiftwidth=2 autoindent expandtab
